package kdev::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'kdev::SchemaClass',
    
    connect_info => {
        dsn => 'dbi:mysql:devdb12',
        user => 'ksankar',
        password => 'mugetsu',
    }
);

=head1 NAME

kdev::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<kdev>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<kdev::SchemaClass>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.61

=head1 AUTHOR

root

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
